In [1]:
import numpy as np


### Suppose we have a dataset which the dog = [0,1,2,3] cat = [4,5,6,7] frog = [8,9,10,11]

In [2]:
dog = np.array([0, 1, 2, 3])
cat = np.array([4, 5, 6, 7])
frog = np.array([8, 8, 10, 11])

### Let's stack these images so we have a matrix 3,4 i.e 3 images with their 4 features

In [3]:
images = np.stack([dog, cat, frog])
images

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  8, 10, 11]])

In [4]:
images.shape

(3, 4)

### To normalize, find the exp of the individal numbers , then divide by its sum

In [5]:
images_exp = np.exp(images)
images_exp

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
          2.00855369e+01],
       [  5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
          1.09663316e+03],
       [  2.98095799e+03,   2.98095799e+03,   2.20264658e+04,
          5.98741417e+04]])

In [6]:
sum_images_exp = np.sum(images_exp, axis=1)
sum_images_exp

array([  3.11928749e+01,   1.70307326e+03,   8.78625235e+04])

In [7]:
1.48413159e+02/1.70307326e+03, 2.71828183e+00/3.11928749e+01

(0.0871443187358834, 0.08714431865336017)

### we have the exponents of the image features and the sum of exp.

In [8]:
norm_images = images_exp.T / sum_images_exp
norm_images

array([[ 0.0320586 ,  0.0320586 ,  0.03392753],
       [ 0.08714432,  0.08714432,  0.03392753],
       [ 0.23688282,  0.23688282,  0.25069239],
       [ 0.64391426,  0.64391426,  0.68145256]])

### Now we have flipped the images around, first column is dog etc
The major reason why we normalize is to scale down the images so that the sum is 1. Let's see if this is true

In [9]:
np.sum(norm_images, axis=0)

array([ 1.,  1.,  1.])

### Let's unstack these images

In [10]:
norm_dog, norm_cat, norm_frog = np.split(norm_images.T, 3)

In [11]:
norm_dog

array([[ 0.0320586 ,  0.08714432,  0.23688282,  0.64391426]])

In [12]:
norm_cat

array([[ 0.0320586 ,  0.08714432,  0.23688282,  0.64391426]])

In [13]:
norm_frog

array([[ 0.03392753,  0.03392753,  0.25069239,  0.68145256]])